import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/ui/theme-provider"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Cabin } from "next/font/google"
import type { ReactNode } from "react"
import "./globals.css"

export const metadata: Metadata = {
	title: "Arcadia",
	description: "Generated by create next app",
}

const font = Cabin({
	subsets: ["latin"],
})

export const dynamic = "force-dynamic"

interface RootLayoutProps {
	children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
	return (
		<ClerkProvider>
			<html lang="fr" suppressHydrationWarning={true}>
				<body className={`${font.className} overflow-hidden antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						disableTransitionOnChange={false}
					>
						{props.children}
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
